### ISSUE TITLE
Sample app crashing

### ISSUE THREAD

**Issue by zaneschepke** [gluon-framework/gluon#57]
Sample app works great on my desktop computer but crashes instantly on my laptop. Same version of Nodejs (16) and both Windows 11 machines.  Any ideas would be much appreciated!

```
[Gluon] starting browser...
[Gluon] found browser chrome (chromium based) at path: C:\Program Files\Google\Chrome\Application\chrome.exe
[Gluon] data path: C:\Users\zanec\OneDrive\Documents\GitHub\gluworld\gluon_data\chrome
[Gluon] connecting to CDP over stdio pipe...
[Gluon] browser: Chrome/110.0.5481.178
[Gluon] acquiring target...
.[Gluon] pipe read closed
file:///C:/Users/zanec/OneDrive/Documents/GitHub/gluworld/node_modules/@gluon-framework/gluon/src/launcher/inject.js:77
    Window.close();
    ^

ReferenceError: Cannot access 'Window' before initialization
```

**Comment by CanadaHonk** [comment]
Was fixed but never released a patch update, will do now.

**Comment by zaneschepke** [comment]
I installed the latest 0.13.4 and crash is still happening but no longer getting the ReferenceError. Crash happens right after "pipe read closed". The app stays running but the browser/app has crashed. 

```
[Gluon] starting browser...
[Gluon] found browser chrome (chromium based) at path: C:\Program Files\Google\Chrome\Application\chrome.exe
[Gluon] data path: C:\Users\zanec\OneDrive\Documents\GitHub\gluworld\gluon_data\chrome
[Gluon] connecting to CDP over stdio pipe...
[Gluon] browser: Chrome/110.0.5481.178
[Gluon] acquiring target...
.[Gluon] pipe read closed
```

**Comment by CanadaHonk** [comment]
Chromium bug, fixed in next commit.
